"""empty message

Revision ID: 37e8c8befc09
Revises: None
Create Date: 2014-07-08 22:04:16.869221

"""

# revision identifiers, used by Alembic.
revision = '37e8c8befc09'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('foo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fooname', sa.String(length=140), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fooname')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('foo')
    ### end Alembic commands ###
