"""empty message

Revision ID: 68d67596ac2
Revises: 37e8c8befc09
Create Date: 2014-07-08 22:10:31.985845

"""

# revision identifiers, used by Alembic.
revision = '68d67596ac2'
down_revision = '37e8c8befc09'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('foo', sa.Column('email', sa.String(length=150), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('foo', 'email')
    ### end Alembic commands ###
